[package]
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
name = "brainwiki"
version = "0.1.0"
[dependencies]
actix-web = "*"
failure = "*"
lazy_static = "*"
pulldown-cmark = "*"
regex = "*"
structopt = "*"
